language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_ACCESS_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master