// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    IIonLogoGithub: typeof import('~icons/ion/logo-github')['default']
    IIonMenuSharp: typeof import('~icons/ion/menu-sharp')['default']
    IIonPause: typeof import('~icons/ion/pause')['default']
    IIonPlay: typeof import('~icons/ion/play')['default']
    IIonSearch: typeof import('~icons/ion/search')['default']
    IIonStop: typeof import('~icons/ion/stop')['default']
    NumberSelect: typeof import('./src/components/NumberSelect.vue')['default']
    PlayControl: typeof import('./src/components/PlayControl/PlayControl.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}

export { };
